### ISSUE TITLE
NETCONF paging

### ISSUE THREAD

**Issue by wisotzky** [netconf-wg/netconf-next#1]
NETCONF get/get-config operations do not provide control about the amount of data being returned. While get-data max-depth can be used to limit the number of hierarchy levels, it does not help if a table contains 100.000's of entries. The way NETCONF works today - you can request either the entire table (all entries or nothing).

To following functionality is requested:
- Option to limit the number of entries returned when reading a list [P0]
- Method to check, if a list/container contains explicitly configured data without the need to read the (entire) list/container [P0]
- Method to get the number of list entries, without the need to reed the entire list [P1]
- Method to get timestamp, when the list of updated the last time [P1]
- Method to retrive a table in chunks aka paging [P1]

**Comment by avtobiff** [comment]
This work is ongoing in the list pagination fro yang-driven protocols internet draft. [0,1]

In RESTCONF it is possible to match on ETag and Last-Modified headers. This is
not possible in NETCONF of course. However, the transaction-id internet draft [2]
might fit as a solution for this problem?

If no updates are made to this ticket I think it should be closed.

[0] https://datatracker.ietf.org/doc/draft-ietf-netconf-list-pagination/
[1] https://datatracker.ietf.org/doc/draft-ietf-netconf-list-pagination-nc/
[2] https://datatracker.ietf.org/doc/draft-ietf-netconf-transaction-id/
