### ISSUE TITLE
RESTCONF-like timestamp/Etag support

### ISSUE THREAD

**Issue by kwatsen** [netconf-wg/netconf-next#12]
The "Last-Modified" and "If-Match" HTTP headers are used in RESTCONF to great effect.

Support for these headers may negate need for partial-locking...

Porting these RPC input parameters to NETCONF would both improve NETCONF and facilitate implementation of servers supporting both protocols.

**Comment by mjethanandani** [comment]
Please see draft-lindblad-netconf-transaction-id or yet to be published draft-ietf-netconf-netconf-etag.
