### ISSUE TITLE
Support for private candidate datastores.

### ISSUE THREAD

**Issue by rgwilton** [netconf-wg/netconf-next#14]

**Comment by mjethanandani** [comment]
Does anyone want to write an id to support this capability? Does not require a big change to RFC 6241.

**Comment by QiufangMa** [comment]
Does this mean each session writes its own private candidate datastore which cannot be seen by other sessions until committed? That's quite insteresting.

**Comment by avtobiff** [comment]
Ongoing work in draft-ietf-netconf-privcand.
