### ISSUE TITLE
Provide private candidate datastores (concurrent transactions)

### ISSUE THREAD

**Issue by abierman** [netconf-wg/netconf-next#47]
The shared candidate is not a good solution for multi-client operation.
A better design would provide private candidate datastores and a better
concurrent transaction model that permitted concurrent edits that do not collide,
and rejected edits which cause a collision.  Need to account for YANG cross-references
that cause validation failures

**Comment by peipeiguo** [comment]
Hi Andy,

I also think shared candidate is not a good solution for multi-client operation. We should provide private candidate datastores. If multi-client operate different configurations without any relation, we should permit concurrency edits.

**Comment by rgwilton** [comment]
For reference: https://www.ietf.org/archive/id/draft-lhotka-netconf-restconf-transactions-00.txt

**Comment by avtobiff** [comment]
This work is on-going in https://datatracker.ietf.org/doc/draft-ietf-netconf-privcand/
